name: PlayTime
main: nikocher
vesrion: ${project.version}
api-version: 1.16
authors: [ nikodim_cheer ]
#depend: [ ]
#
#commands:
#
#  playtime:
#    descrtiption: show the player time spent for 1-30 days
#    usage: /<command> <player> [days=1]
#    aliases: [getpt]