#nameof#
nameof_main: mineguis
nameof_pack: minepack
nameof_log: "[mineguis] "
#sizeof#
sizeof_main: 3 # main menu lines
sizeof_maxm: 6 # maximal menu lines
sizeof_minm: 1 # minimal menu lines
sizeof_usem: 3 # used by default menu lines